### ISSUE TITLE
建议把正确答案做个标记，或者题目后面加个正确答案

### ISSUE THREAD

**Issue by BG7ZAG** [bd8bzy/crac-exam-b#1]
这样容易看到正确答案是什么，然后下面是解析~

**Comment by BG7ZAG** [comment]
看到提示说明了，如果没注意看开头提示还真不知道正确答案都是A

**Comment by bd8bzy** [comment]
抱歉才看到信息。
第一个选项就是答案哈，crac的题库一直是这样的惯例。
抱歉说明不太明显，我回头加重提示下吧～

BG7ZAG ***@***.***> 于2023年9月7日周四 10:20写道：

**Comment by BG7ZAG** [comment]
> 

一直用智普app做题，没注意这个惯例
![00693327](https://github.com/bd8bzy/crac-exam-b/assets/16408650/f449f082-533a-440a-9fa0-2d5e11e0f939)
